version: "3.9"

services:

  g-frame:
    hostname: g-frame
    image: g-frame
    build:
      context: ./
      dockerfile: gframe-dockerfile
    ports:
      - "4200:80"
    networks:
      - frontend

  l-app1:
    hostname: l-app1
    image: l-app1
    build:
      context: ./
      dockerfile: lapp1-dockerfile
    ports:
      - "4201:80"
    networks:
      - frontend

networks:
  frontend:

  # docker-compose up -d
